### ISSUE TITLE
Body text in .js file

### ISSUE THREAD

**Issue by evelynmitchell** [upsuper/rust-cheatsheet#3]
I was wondering why the body text is within the .js file, instead of in a file which would be more obvious like .json

**Comment by upsuper** [comment]
Because json is hard to write by hand (annoying syntax requirements e.g. keys must be quoted, no trailing comma), and reading other structural format in JavaScript likely require extra libraries.

That being said, I may at some point rewrite the page generation in Rust, and use yaml to store the data instead when I got some time.

**Comment by upsuper** [comment]
FYI, the content has been rewritten in YAML since a while ago. If you want to use that data, you can now find it inside `data` directory.
