### ISSUE TITLE
Odd zoom level?

### ISSUE THREAD

**Issue by Lonami** [upsuper/rust-cheatsheet#4]
Is this normal? I.e., is it intended that everything looks so small?
![image](https://user-images.githubusercontent.com/6297805/57018326-58253780-6c23-11e9-84d5-c04b7654691b.png)

1366x768 display, Firefox 66 on Linux Mint.

I would hope "single" fixed the issue, but it did not:
![image](https://user-images.githubusercontent.com/6297805/57018358-8440b880-6c23-11e9-8008-d4a2f209dfa3.png)

**Comment by upsuper** [comment]
It is normal and intentional, so that it is easy to (almost) see the whole cheatsheet in a single screen. You can use browser zooming to zoom in.

That's being said, I have added a "large" mode a while ago, and I just added a link for that mode as well in 4e05c9d0e104dee2ba1c2a470140231ee250ec7f. Hope that would be useful.

**Comment by Lonami** [comment]
Okay, thank you.
